languageCode = "zh-cn"
languageName = "Simplified Chinese"
weight = 1
title = "404NotFound"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "404NotFound"
  image = "avatar.jpg"
  headline = "Lost & Found"
  bio = ""
links = [
  { email = "mailto:admin@wavelee.top" },
  { link = "https://www.wavelee.top" },
  { github = "https://github.com/Wave233Lee" },
  { steam = "https://steamcommunity.com/profiles/76561198236119120" },
  { x-twitter = "https://twitter.com/WaveLee1997" },
]
